### Login
# @name login
POST http://localhost:3000/auths/login
Content-Type: application/json

{
    "email":"facebok@gmail.com",
    "password":"admin"
}

### Login the admin
GET http://localhost:3000/jobOffers
Content-Type: application/json

### Login the admin
POST http://localhost:3000/jobOffers/create
Content-Type: application/json

{
    "title": "titre4",
    "contactMail": "mail2@contact.com",
    "contractType": "CDD",
    "description": "un job qui consiste en jsp...",
    "idCompany": 1
}


### Login the admin
GET http://localhost:3000/jobOffers/company/getAllMyJobOffers/
Authorization: {{login.response.body.token}}
