### Login
# @name login
POST http://localhost:3000/auths/login
Content-Type: application/json

{
    "email":"facebok@gmail.com",
    "password":"admin"
}


### get a job offer based on its id
GET http://localhost:3000/jobOffers/id/2
Content-Type: application/json


### create a job offer
POST http://localhost:3000/jobOffers/create
Content-Type: application/json

{
    "title": "titre4",
    "contactMail": "mail2@contact.com",
    "contractType": "CDD",
    "description": "un job qui consiste en jsp...",
    "idCompany": 1
}


### Login the admin
GET http://localhost:3000/jobOffers/company/getAllMyJobOffers/
Authorization: {{login.response.body.token}}

### Login the admin
GET http://localhost:3000/jobOffers/getAll/
Authorization: {{login.response.body.token}}

### create a job offer
POST http://localhost:3000/jobOffers/createIntrested
Content-Type: application/json

{
    "idOffer": 1,
    "idUser": 2
}
